---
name: buildrone-git
kind: pipeline
type: docker

steps:
    - name: build
      image: golang:latest
      commands:
        - apt update -y
        - curl -sL https://git.io/goreleaser > goreleaser.sh
        - chmod +x goreleaser.sh
        - ./goreleaser.sh --snapshot --skip-publish --rm-dist
        - wget https://builds.hrfee.pw/upload.py
        - pip3 install requests
        - bash -c 'python3 upload.py https://builds.hrfee.pw hrfee jfa-go ./dist/*.tar.gz'
      environment:
          BUILDRONE_KEY:
              from_secret: BUILDRONE_KEY

