when:
  - event: push
    branch: main

clone:
    git:
        image: woodpeckerci/plugin-git
        settings:
            tags: true

steps:
  - name: build
    image: docker.io/golang:bookworm
    commands:
      - apt update -y
      - apt install python3-requests -y
      - curl -sfL https://goreleaser.com/static/run > goreleaser
      - chmod +x goreleaser
      - ./goreleaser --snapshot --skip=publish --clean
  - name: buildrone
    image: docker.io/golang:bookworm
    environment:
        BUILDRONE_KEY:
            from_secret: BUILDRONE_KEY
    commands:
      - wget https://builds.hrfee.pw/upload.py
      - bash -c 'python3 upload.py https://builds.hrfee.pw hrfee buildrone --upload ./dist/*.tar.gz'
